# Generated by Django 4.2.1 on 2023-05-22 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_category_listing_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
