# Generated by Django 4.2.2 on 2023-06-13 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_user_follower"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="follower",
            new_name="followers",
        ),
    ]
