# Generated by Django 4.2.2 on 2023-07-02 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date_todo_on",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
