# Generated by Django 4.2.2 on 2023-07-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0004_task_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_todo_on",
            field=models.DateField(),
        ),
    ]
